language: cpp

compiler:
  - clang
  - g++

notifications:
  recipients:
    - lasse.schuirmann@gmail.com
    - mak95@arcor.de
  email:
    on_failure: always
    on_success: always

before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.8

script:
    - g++ --version
    - make debug
