language: cpp

compiler:
  - clang
  - g++

notifications:
  recipients:
    - lasse.schuirmann@gmail.com
    - mak95@arcor.de
  email:
    on_failure: always
    on_success: always

before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - g++ --version
    - make debug
